In [7]:
import numpy as np

arr1 = [11, 22, 33, 44]
print(arr1)

arr2 = ([10, 20, 30, 40],
        [50, 60, 70, 80])
print(arr2)

ar = np.array([100, 200, 300])
print(ar)

zero = np.zeros((3, 2))
print("Zero Array:\n", zero)

one = np.ones((2, 4))
print("Ones Array:\n", one)


[11, 22, 33, 44]
([10, 20, 30, 40], [50, 60, 70, 80])
[100 200 300]
Zero Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
identity = np.eye(3)
print(identity)

ls = np.linspace(5, 25, 5)
print(ls)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 5. 10. 15. 20. 25.]
[[40 25 29]
 [40 47 32]
 [47 13  7]]
Shape: (4, 3)
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [8]:
randnum = ((np.random.rand(3, 3)) * 50).astype(int)
print(randnum)

ashp = np.shape(arr2)
print("Shape:", ashp)

arr = np.arange(10, 22).reshape(4, 3)
print(arr)

[[44  7 19]
 [11 22 39]
 [ 3 31 15]]
Shape: (2, 4)
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [2]:
import numpy as np

array1 = ([10, 20, 30, 40],
          [50, 60, 70, 80])

array2 = ([15, 25, 35, 45],
          [55, 65, 75, 85])

addition = np.sum(array2)
print("Sum:", addition)

print("Mean:", np.mean(array1))

print("Standard Deviation:", np.std(array1))



Sum: 400
Mean: 45.0
Standard Deviation: 22.9128784747792
Minimum: 10
Maximum: 80
ArgMin: 0
ArgMax: 7


In [9]:
print("Minimum:", np.min(array1))

print("Maximum:", np.max(array1))

print("ArgMin:", np.argmin(array1))

print("ArgMax:", np.argmax(array1))

Minimum: 10
Maximum: 80
ArgMin: 0
ArgMax: 7


In [3]:
import numpy as np

X = np.array([[2, 4],
              [6, 8]])

Y = np.array([[1, 3],
              [5, 7]])

dot_product = np.dot(X, Y)
print(dot_product)

mat = np.arange(12, 20).reshape(2, 4)
print(mat)

print("Transpose:\n", mat.T)

sorts = np.sort([12, 4, 18, 2, 9, 25])
print(sorts)

[[22 34]
 [46 74]]
[[12 13 14 15]
 [16 17 18 19]]
Transpose:
 [[12 16]
 [13 17]
 [14 18]
 [15 19]]
[ 2  4  9 12 18 25]


In [4]:
import numpy as np

arr1 = np.array([7, 14, 21, 28, 35, 42])

arr2 = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18],
    [20, 22, 24]
])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

zeros = np.zeros((2, 5))
ones = np.ones((4, 2))
identity = np.eye(4)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

arange_arr = np.arange(5, 55, 5)
linspace_arr = np.linspace(10, 50, 6)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

rand_arr = np.random.rand(2, 4)
print(rand_arr)

1D Array: [ 7 14 21 28 35 42]
2D Array:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Arange: [ 5 10 15 20 25 30 35 40 45 50]
Linspace: [10. 18. 26. 34. 42. 50.]
[[0.04649615 0.8774257  0.78757565 0.17274453]
 [0.03412208 0.18657029 0.83628863 0.18383978]]


In [5]:
import numpy as np

matrix = np.arange(21, 33).reshape(4, 3)
print("Matrix:\n", matrix)

print("Transpose:\n", matrix.T)

arr = np.array([5, 15, 25, 35])

print("Original Array:", arr)

print("Array - 5:", arr - 5)

print("Array Squared:", arr ** 2)

print("Sum:", np.sum(arr))

print("Mean:", np.mean(arr))

print("Standard Deviation:", np.std(arr))

A = np.array([[2, 3],
              [4, 5]])

B = np.array([[6, 7],
              [8, 9]])

print("Matrix Multiplication:\n", np.dot(A, B))

unsorted = np.array([11, 3, 7, 15, 2, 9])

print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]]
Transpose:
 [[21 24 27 30]
 [22 25 28 31]
 [23 26 29 32]]
Original Array: [ 5 15 25 35]
Array - 5: [ 0 10 20 30]
Array Squared: [  25  225  625 1225]
Sum: 80
Mean: 20.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[36 41]
 [64 73]]
Sorted Array: [ 2  3  7  9 11 15]
